[project]
name = "coral-schemas"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "numpy~=2.4.1",
    "opencv-python~=4.13.0.90",
    "pillow>=12.1.0",
    "pycocotools>=2.0.11",
    "pydantic~=2.12.5",
    "scipy~=1.17.0",
]
