[project]
name = "coral-schemas"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "opencv-python",
    "pycocotools",
    "pydantic",
    "scipy",
    "scipy-stubs",
]
